site_name: PySpark Dubber
site_url: https://frapa.github.com/pyspark-dubber
repo_url: https://github.com/frapa/pyspark-dubber
repo_name: frapa/pyspark-dubber
theme:
  name: material
  icon:
    logo: material/account-cowboy-hat
  palette:
    primary: green
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.tabs
      - navigation.sections
      - navigation.path
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
markdown_extensions:
  - tables
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg